# application-local.example.properties

# Copie este arquivo para `application-dev.properties`
# e preencha com seu user/senha local do MySQL

spring.datasource.username=SEU_USUARIO_DO_MYSQL
spring.datasource.password=SUA_SENHA_DO_MYSQL
