spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cesar_edu

spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.flyway.enabled=false

spring.profiles.active=dev
spring.sql.init.separator=@@