app.database.host=db
app.database.port=5432
app.database.name=cesaredu

spring.datasource.url=jdbc:postgresql://db:5432/cesaredu
spring.datasource.username=cesaredu_user
spring.datasource.password=cesaredu_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always