spring.application.name=backend

app.database.host=localhost
app.database.port=5432
app.database.name=cesar_edu

spring.datasource.url=jdbc:postgresql://localhost:5432/cesar_edu

spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.flyway.enabled=false

spring.profiles.active=dev