CREATE TABLE IF NOT EXISTS usuario(
                        cpf CHAR(11) PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        senha VARCHAR(255) NOT NULL,
                        logradouro VARCHAR(255),
                        numero INT,
                        cep CHAR(8)
);
@@
CREATE TABLE IF NOT EXISTS telefone(
                         cpf CHAR(11) REFERENCES usuario(cpf) ON DELETE CASCADE,
                         numero CHAR(11),
                         PRIMARY KEY (cpf, numero)
);
@@
CREATE TABLE IF NOT EXISTS professor(
                          cpf_professor CHAR(11) PRIMARY KEY REFERENCES usuario(cpf) ON DELETE CASCADE
);
@@
CREATE TABLE IF NOT EXISTS certificacoes(
                              cpf_professor CHAR(11) REFERENCES professor(cpf_professor) ON DELETE CASCADE,
                              titulo_certificado VARCHAR(255),
                              PRIMARY KEY (cpf_professor, titulo_certificado)
);
@@
CREATE TABLE IF NOT EXISTS aluno(
                      cpf_aluno CHAR(11) PRIMARY KEY REFERENCES usuario(cpf) ON DELETE CASCADE
);
@@
CREATE TABLE IF NOT EXISTS curso(
                      id_curso BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                      nome VARCHAR(255) NOT NULL,
                      preco DECIMAL(10, 2) NOT NULL CHECK(preco >= 0),
                      descricao TEXT
);
@@
CREATE TABLE IF NOT EXISTS leciona(
                        cpf_professor CHAR(11) REFERENCES professor(cpf_professor) ON DELETE CASCADE,
                        id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                        PRIMARY KEY (cpf_professor, id_curso)
);
@@
CREATE TABLE IF NOT EXISTS categoria(
                          id_categoria BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                          nome_da_categoria VARCHAR(255) NOT NULL
);
@@
CREATE TABLE IF NOT EXISTS possui(
                       id_categoria BIGINT REFERENCES categoria(id_categoria) ON DELETE CASCADE,
                           id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                       PRIMARY KEY (id_categoria, id_curso)
);
@@
CREATE TABLE IF NOT EXISTS compra(
                       id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                       cpf_aluno CHAR(11) REFERENCES aluno(cpf_aluno) ON DELETE CASCADE,
                       data_compra DATE NOT NULL DEFAULT now(),
                       PRIMARY KEY (id_curso, cpf_aluno)
);
@@
CREATE TABLE IF NOT EXISTS certificado_curso(
                                  id_certificado BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                                  id_curso_concluido BIGINT,
                                  cpf_aluno_graduado CHAR(11),
                                  data_certificado DATE NOT NULL DEFAULT now(),
                                  PRIMARY KEY (id_certificado, id_curso_concluido, cpf_aluno_graduado),
                                  FOREIGN KEY (id_curso_concluido, cpf_aluno_graduado)
                                      REFERENCES compra(id_curso, cpf_aluno)
                                      ON DELETE CASCADE
);
@@
CREATE TABLE IF NOT EXISTS modulo(
                       id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                       id_modulo BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                       titulo VARCHAR(255) NOT NULL,
                       carga_horaria INT NOT NULL CHECK(carga_horaria > 0),
                       descricao TEXT,
                       PRIMARY KEY(id_curso, id_modulo)
);
@@
CREATE TABLE IF NOT EXISTS aula(
                     id_aula BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                     id_curso BIGINT,
                     id_modulo BIGINT,
                     descricao TEXT,
                     link_do_video VARCHAR(255) NOT NULL,
                     titulo VARCHAR(255) NOT NULL,
                     PRIMARY KEY(id_aula, id_curso, id_modulo),
                     UNIQUE (id_aula),
                     FOREIGN KEY (id_curso, id_modulo)
                         REFERENCES modulo(id_curso, id_modulo)
                         ON DELETE CASCADE
);
@@
CREATE TABLE IF NOT EXISTS material(
                         id_material BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                         id_aula BIGINT,
                         id_curso BIGINT,
                         id_modulo BIGINT,
                         link_material VARCHAR(255) NOT NULL,
                         nome VARCHAR(255) NOT NULL,
                         PRIMARY KEY(id_material, id_aula, id_curso, id_modulo),
                         FOREIGN KEY (id_aula, id_curso, id_modulo)
                             REFERENCES aula(id_aula, id_curso, id_modulo)
                             ON DELETE CASCADE
);
@@
CREATE TABLE IF NOT EXISTS assistir(
                         id_aula BIGINT,
                         id_curso BIGINT,
                         id_modulo BIGINT,
                         cpf_aluno CHAR(11) REFERENCES aluno(cpf_aluno) ON DELETE CASCADE,
                         data_assistida DATE NOT NULL DEFAULT now(),
                         PRIMARY KEY(cpf_aluno, id_aula, id_curso, id_modulo),
                         FOREIGN KEY (id_aula, id_curso, id_modulo)
                             REFERENCES aula(id_aula, id_curso, id_modulo)
                             ON DELETE CASCADE
);
@@
CREATE TABLE IF NOT EXISTS comentario(
                           id_comentario BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                           id_aula BIGINT NOT NULL REFERENCES aula(id_aula) ON DELETE CASCADE,
                           id_curso BIGINT NOT NULL,
                           cpf_aluno CHAR(11),
                           cpf_professor CHAR(11) REFERENCES professor(cpf_professor),
                           data_criacao DATE NOT NULL DEFAULT now(),
                           conteudo TEXT,
                           comentario_pai BIGINT REFERENCES comentario(id_comentario) ON DELETE SET NULL,
                           CHECK (
                               (cpf_aluno IS NOT NULL AND cpf_professor IS NULL) OR
                               (cpf_aluno IS NULL AND cpf_professor IS NOT NULL)
                               ),
                           FOREIGN KEY (id_curso, cpf_aluno)
                               REFERENCES compra(id_curso, cpf_aluno),
                           FOREIGN KEY (cpf_professor, id_curso)
                               REFERENCES leciona(cpf_professor, id_curso)
);
@@
CREATE OR REPLACE VIEW vw_progresso_aluno_curso AS
SELECT
    a.cpf_aluno,
    c.id_curso,
    c.nome AS nome_curso,
    COUNT(DISTINCT (au.id_curso, au.id_modulo, au.id_aula)) AS total_aulas,
    COUNT(DISTINCT (ass.id_curso, ass.id_modulo, ass.id_aula)) AS aulas_assistidas,
    ROUND(
            (COUNT(DISTINCT ass.id_aula)::numeric /
        NULLIF(COUNT(DISTINCT au.id_aula), 0)) * 100,
            2
    ) AS percentual_conclusao
FROM aluno a
         JOIN compra co
              ON co.cpf_aluno = a.cpf_aluno
         JOIN curso c
              ON c.id_curso = co.id_curso
         JOIN modulo m
              ON m.id_curso = c.id_curso
         JOIN aula au
              ON au.id_curso = m.id_curso
                  AND au.id_modulo = m.id_modulo
         LEFT JOIN assistir ass
                   ON ass.cpf_aluno = a.cpf_aluno
                       AND ass.id_curso = c.id_curso
                       AND ass.id_modulo = au.id_modulo
                       AND ass.id_aula = au.id_aula
WHERE c.preco > 0
GROUP BY
    a.cpf_aluno,
    c.id_curso,
    c.nome;
@@
CREATE OR REPLACE VIEW vw_resumo_geral_cursos AS
SELECT
    c.id_curso,
    c.nome AS nome_curso,
    c.preco,
    COUNT(co.cpf_aluno) AS total_compras,
    COUNT(co.cpf_aluno) * c.preco AS receita_estimada,
    (
        SELECT AVG(c2.preco)
        FROM curso c2
    ) AS media_preco_geral,
    CASE
        WHEN c.preco > (
            SELECT AVG(c2.preco)
            FROM curso c2
        ) THEN 'ACIMA_DA_MEDIA'
        WHEN c.preco = (
            SELECT AVG(c2.preco)
            FROM curso c2
        ) THEN 'NA_MEDIA'
        ELSE 'ABAIXO_DA_MEDIA'
        END AS classificacao_preco
FROM curso c
         LEFT JOIN compra co
                   ON co.id_curso = c.id_curso
GROUP BY
    c.id_curso,
    c.nome,
    c.preco;
@@
CREATE INDEX IF NOT EXISTS idx_aula_id_curso_id_modulo
    ON aula (id_curso, id_modulo);
@@
CREATE INDEX IF NOT EXISTS idx_assistir_id_curso_cpf_aluno
    ON assistir (id_curso, cpf_aluno,id_modulo,
    id_aula);
@@
CREATE OR REPLACE FUNCTION calcular_desconto(
    IN preco NUMERIC,
    IN desconto NUMERIC
)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
preco_com_desconto NUMERIC;
BEGIN
    IF desconto > 100 OR desconto < 0 THEN
        RAISE EXCEPTION 'O desconto deve estar entre 0 e 100%%';
END IF;

    preco_com_desconto := preco - (preco * (desconto / 100));

RETURN ROUND(preco_com_desconto, 2);
END;
$$;
@@
CREATE OR REPLACE FUNCTION calcular_carga_horaria_total(
       IN v_id_curso BIGINT
)
       RETURNS INT
       LANGUAGE plpgsql
       AS $$

       DECLARE horas_totais INT;

       BEGIN
       SELECT SUM(carga_horaria)
       INTO horas_totais
       FROM modulo
       WHERE id_curso = v_id_curso;

       RETURN COALESCE(horas_totais,0);
       END;
       $$;
@@
CREATE OR REPLACE PROCEDURE aplicar_desconto_em_categoria(
       IN in_categoria VARCHAR,
       IN desconto DOUBLE PRECISION
)
       LANGUAGE plpgsql
       AS $$

       DECLARE v_id_categoria BIGINT;

       BEGIN

       SELECT id_categoria
       INTO v_id_categoria
       FROM categoria c
       WHERE c.nome_da_categoria = in_categoria;

        IF v_id_categoria IS NULL THEN
                RAISE EXCEPTION 'Categoria "%" não encontrada.', in_categoria;
        END IF;

       UPDATE curso
       SET preco = calcular_desconto(preco, desconto::NUMERIC)
       WHERE id_curso IN (
           SELECT c.id_curso
           FROM curso c
           JOIN possui p
           ON c.id_curso = p.id_curso AND p.id_categoria = v_id_categoria
           );

       END;
       $$;
        @@
CREATE TABLE IF NOT EXISTS alunos_inativos (
    cpf_aluno CHAR(11) NOT NULL,
    nome_aluno VARCHAR(255) NOT NULL,

    id_curso BIGINT NOT NULL,
    nome_curso VARCHAR(255) NOT NULL,

    data_compra DATE NOT NULL,
    ultima_aula_assistida DATE,
    data_referencia_inatividade DATE NOT NULL,

    dias_inativo INT NOT NULL ,

    motivo VARCHAR(50) NOT NULL,
    data_atualizacao TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY (cpf_aluno, id_curso),

    FOREIGN KEY (id_curso, cpf_aluno)
    REFERENCES compra(id_curso, cpf_aluno)
    ON DELETE CASCADE
);
@@

CREATE OR REPLACE PROCEDURE atualizar_alunos_inativos()
    LANGUAGE plpgsql
    AS $$
    DECLARE
    cur_alunos CURSOR FOR
    SELECT
        co.cpf_aluno,
        u.nome AS nome_aluno,
        co.id_curso,
        c.nome AS nome_curso,
        co.data_compra,
        MAX(ass.data_assistida) AS ultima_aula_assistida
    FROM compra co
             JOIN aluno a
                  ON a.cpf_aluno = co.cpf_aluno
             JOIN usuario u
                  ON u.cpf = a.cpf_aluno
             JOIN curso c
                  ON c.id_curso = co.id_curso
             LEFT JOIN assistir ass
                       ON ass.cpf_aluno = co.cpf_aluno
                           AND ass.id_curso = co.id_curso
    GROUP BY
        co.cpf_aluno,
        u.nome,
        co.id_curso,
        c.nome,
        co.data_compra;

    v_registro RECORD;
        v_data_referencia DATE;
        v_dias_inativo INT;
        v_motivo VARCHAR(50);
    BEGIN
    OPEN cur_alunos;

    LOOP
    FETCH cur_alunos INTO v_registro;
            EXIT WHEN NOT FOUND;

            v_data_referencia := COALESCE(
                v_registro.ultima_aula_assistida,
                v_registro.data_compra
            );

            v_dias_inativo := CURRENT_DATE - v_data_referencia;

            IF v_registro.ultima_aula_assistida IS NULL THEN
                v_motivo := 'NUNCA_ASSISTIU';
    ELSE
                v_motivo := 'SEM_ACESSO_RECENTE';
    END IF;

            IF v_dias_inativo > 1 THEN

                INSERT INTO alunos_inativos (
                    cpf_aluno,
                    nome_aluno,
                    id_curso,
                    nome_curso,
                    data_compra,
                    ultima_aula_assistida,
                    data_referencia_inatividade,
                    dias_inativo,
                    motivo,
                    data_atualizacao
                )
                VALUES (
                    v_registro.cpf_aluno,
                    v_registro.nome_aluno,
                    v_registro.id_curso,
                    v_registro.nome_curso,
                    v_registro.data_compra,
                    v_registro.ultima_aula_assistida,
                    v_data_referencia,
                    v_dias_inativo,
                    v_motivo,
                    now()
                )
                ON CONFLICT (cpf_aluno, id_curso)
                DO UPDATE SET
                    nome_aluno = EXCLUDED.nome_aluno,
                    nome_curso = EXCLUDED.nome_curso,
                    data_compra = EXCLUDED.data_compra,
                    ultima_aula_assistida = EXCLUDED.ultima_aula_assistida,
                    data_referencia_inatividade = EXCLUDED.data_referencia_inatividade,
                    dias_inativo = EXCLUDED.dias_inativo,
                    motivo = EXCLUDED.motivo,
                    data_atualizacao = now();

    ELSE

    DELETE FROM alunos_inativos ai
    WHERE ai.cpf_aluno = v_registro.cpf_aluno
      AND ai.id_curso = v_registro.id_curso;

    END IF;
    END LOOP;

    CLOSE cur_alunos;
    END;
    $$;
    @@

CREATE TABLE IF NOT EXISTS log_preco_curso (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_curso BIGINT,
    preco_antigo DECIMAL(10,2),
    preco_novo DECIMAL(10,2),
    data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_banco VARCHAR(50)
);
@@

CREATE OR REPLACE FUNCTION fn_log_preco_curso()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.preco IS DISTINCT FROM NEW.preco THEN
        INSERT INTO log_preco_curso (
            id_curso,
            preco_antigo,
            preco_novo,
            usuario_banco
        )
        VALUES (
            NEW.id_curso,
            OLD.preco,
            NEW.preco,
            current_user
        );
END IF;

RETURN NEW;
END;
$$;
@@

DROP TRIGGER IF EXISTS trg_auditoria_preco_curso ON curso;
@@

CREATE TRIGGER trg_auditoria_preco_curso
AFTER UPDATE ON curso
            FOR EACH ROW
            EXECUTE FUNCTION fn_log_preco_curso();
@@

CREATE OR REPLACE FUNCTION fn_verificar_compra_antes_assistir()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM compra co
        WHERE co.id_curso = NEW.id_curso
          AND co.cpf_aluno = NEW.cpf_aluno
    ) THEN
        RAISE EXCEPTION 'O aluno % não pode assistir aulas do curso %, pois não comprou o curso.',
            NEW.cpf_aluno,
            NEW.id_curso;
END IF;

RETURN NEW;
END;
$$;
@@

DROP TRIGGER IF EXISTS trg_verificar_compra_antes_assistir ON assistir;
@@

CREATE TRIGGER trg_verificar_compra_antes_assistir
BEFORE INSERT OR UPDATE ON assistir
                       FOR EACH ROW
                       EXECUTE FUNCTION fn_verificar_compra_antes_assistir();
@@

CREATE OR REPLACE FUNCTION fn_verficar_conclusao_do_curso_liberar_certificado()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
v_total_aulas INT;
    v_aulas_assistidas INT;
BEGIN
SELECT COUNT(*)
INTO v_total_aulas
FROM aula a
WHERE a.id_curso = NEW.id_curso_concluido;

IF v_total_aulas = 0 THEN
        RAISE EXCEPTION
            'O curso em questão não possui aulas cadastradas';
END IF;

SELECT COUNT(DISTINCT (ass.id_curso, ass.id_modulo, ass.id_aula))
INTO v_aulas_assistidas
FROM assistir ass
WHERE ass.id_curso = NEW.id_curso_concluido
  AND ass.cpf_aluno = NEW.cpf_aluno_graduado;

IF v_total_aulas <> v_aulas_assistidas THEN
        RAISE EXCEPTION
        'Certificado negado: aluno não concluiu todas as aulas do curso';
END IF;

RETURN NEW;
END;
$$;
@@

DROP TRIGGER IF EXISTS trg_verficar_conclusao_do_curso_liberar_certificado ON certificado_curso;
@@

CREATE TRIGGER trg_verficar_conclusao_do_curso_liberar_certificado
    BEFORE INSERT ON certificado_curso
    FOR EACH ROW
    EXECUTE FUNCTION fn_verficar_conclusao_do_curso_liberar_certificado();
@@

CREATE INDEX IF NOT EXISTS idx_aula_titulo
    ON aula(id_curso,id_modulo,titulo);
@@

CREATE INDEX IF NOT EXISTS idx_modulo_titulo
    ON modulo(id_curso,titulo);
@@