CREATE TABLE IF NOT EXISTS usuario(
                        cpf CHAR(11) PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        senha VARCHAR(255) NOT NULL,
                        logradouro VARCHAR(255),
                        numero INT,
                        cep CHAR(8)
);

CREATE TABLE IF NOT EXISTS telefone(
                         cpf CHAR(11) REFERENCES usuario(cpf) ON DELETE CASCADE,
                         numero CHAR(11),
                         PRIMARY KEY (cpf, numero)
);

CREATE TABLE IF NOT EXISTS professor(
                          cpf_professor CHAR(11) PRIMARY KEY REFERENCES usuario(cpf) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS certificacoes(
                              cpf_professor CHAR(11) REFERENCES professor(cpf_professor) ON DELETE CASCADE,
                              titulo_certificado VARCHAR(255),
                              PRIMARY KEY (cpf_professor, titulo_certificado)
);

CREATE TABLE IF NOT EXISTS aluno(
                      cpf_aluno CHAR(11) PRIMARY KEY REFERENCES usuario(cpf) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS curso(
                      id_curso BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                      nome VARCHAR(255) NOT NULL,
                      preco DECIMAL(10, 2) NOT NULL CHECK(preco >= 0),
                      descricao TEXT
);

CREATE TABLE IF NOT EXISTS leciona(
                        cpf_professor CHAR(11) REFERENCES professor(cpf_professor) ON DELETE CASCADE,
                        id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                        PRIMARY KEY (cpf_professor, id_curso)
);

CREATE TABLE IF NOT EXISTS categoria(
                          id_categoria BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                          nome_da_categoria VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS possui(
                       id_categoria BIGINT REFERENCES categoria(id_categoria) ON DELETE CASCADE,
                       id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                       PRIMARY KEY (id_categoria, id_curso)
);

CREATE TABLE IF NOT EXISTS compra(
                       id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                       cpf_aluno CHAR(11) REFERENCES aluno(cpf_aluno) ON DELETE CASCADE,
                       data_compra DATE NOT NULL DEFAULT now(),
                       PRIMARY KEY (id_curso, cpf_aluno)
);

CREATE TABLE IF NOT EXISTS certificado_curso(
                                  id_certificado BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                                  id_curso_concluido BIGINT,
                                  cpf_aluno_graduado CHAR(11),
                                  data_certificado DATE NOT NULL DEFAULT now(),
                                  PRIMARY KEY (id_certificado, id_curso_concluido, cpf_aluno_graduado),
                                  FOREIGN KEY (id_curso_concluido, cpf_aluno_graduado)
                                      REFERENCES compra(id_curso, cpf_aluno)
                                      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS modulo(
                       id_curso BIGINT REFERENCES curso(id_curso) ON DELETE CASCADE,
                       id_modulo BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                       titulo VARCHAR(255) NOT NULL,
                       carga_horaria INT NOT NULL CHECK(carga_horaria > 0),
                       descricao TEXT,
                       PRIMARY KEY(id_curso, id_modulo)
);

CREATE TABLE IF NOT EXISTS aula(
                     id_aula BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                     id_curso BIGINT,
                     id_modulo BIGINT,
                     descricao TEXT,
                     link_do_video VARCHAR(255) NOT NULL,
                     titulo VARCHAR(255) NOT NULL,
                     PRIMARY KEY(id_aula, id_curso, id_modulo),
                     UNIQUE (id_aula),
                     FOREIGN KEY (id_curso, id_modulo)
                         REFERENCES modulo(id_curso, id_modulo)
                         ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS material(
                         id_material BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                         id_aula BIGINT,
                         id_curso BIGINT,
                         id_modulo BIGINT,
                         link_material VARCHAR(255) NOT NULL,
                         nome VARCHAR(255) NOT NULL,
                         PRIMARY KEY(id_material, id_aula, id_curso, id_modulo),
                         FOREIGN KEY (id_aula, id_curso, id_modulo)
                             REFERENCES aula(id_aula, id_curso, id_modulo)
                             ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS assistir(
                         id_aula BIGINT,
                         id_curso BIGINT,
                         id_modulo BIGINT,
                         cpf_aluno CHAR(11) REFERENCES aluno(cpf_aluno) ON DELETE CASCADE,
                         data_assistida DATE NOT NULL DEFAULT now(),
                         PRIMARY KEY(cpf_aluno, id_aula, id_curso, id_modulo),
                         FOREIGN KEY (id_aula, id_curso, id_modulo)
                             REFERENCES aula(id_aula, id_curso, id_modulo)
                             ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comentario(
                           id_comentario BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                           id_aula BIGINT NOT NULL REFERENCES aula(id_aula) ON DELETE CASCADE,
                           id_curso BIGINT NOT NULL,
                           cpf_aluno CHAR(11),
                           cpf_professor CHAR(11) REFERENCES professor(cpf_professor),
                           data_criacao DATE NOT NULL DEFAULT now(),
                           conteudo TEXT,
                           comentario_pai BIGINT REFERENCES comentario(id_comentario) ON DELETE SET NULL,
                           CHECK (
                               (cpf_aluno IS NOT NULL AND cpf_professor IS NULL) OR
                               (cpf_aluno IS NULL AND cpf_professor IS NOT NULL)
                               ),
                           FOREIGN KEY (id_curso, cpf_aluno)
                               REFERENCES compra(id_curso, cpf_aluno),
                           FOREIGN KEY (cpf_professor, id_curso)
                               REFERENCES leciona(cpf_professor, id_curso)
);

CREATE OR REPLACE VIEW vw_progresso_aluno_curso AS
SELECT
    a.cpf_aluno,
    c.id_curso,
    c.nome AS nome_curso,
    COUNT(DISTINCT au.id_aula) AS total_aulas,
    COUNT(DISTINCT ass.id_aula) AS aulas_assistidas,
    ROUND(
            (COUNT(DISTINCT ass.id_aula)::numeric /
        NULLIF(COUNT(DISTINCT au.id_aula), 0)) * 100,
            2
    ) AS percentual_conclusao
FROM aluno a
         JOIN compra co
              ON co.cpf_aluno = a.cpf_aluno
         JOIN curso c
              ON c.id_curso = co.id_curso
         JOIN modulo m
              ON m.id_curso = c.id_curso
         JOIN aula au
              ON au.id_curso = m.id_curso
                  AND au.id_modulo = m.id_modulo
         LEFT JOIN assistir ass
                   ON ass.cpf_aluno = a.cpf_aluno
                       AND ass.id_curso = c.id_curso
                       AND ass.id_modulo = au.id_modulo
                       AND ass.id_aula = au.id_aula
WHERE c.preco > 0
GROUP BY
    a.cpf_aluno,
    c.id_curso,
    c.nome;

CREATE OR REPLACE VIEW vw_resumo_geral_cursos AS
SELECT
    c.id_curso,
    c.nome AS nome_curso,
    c.preco,
    COUNT(co.cpf_aluno) AS total_compras,
    COUNT(co.cpf_aluno) * c.preco AS receita_estimada,
    (
        SELECT AVG(c2.preco)
        FROM curso c2
    ) AS media_preco_geral,
    CASE
        WHEN c.preco > (
            SELECT AVG(c2.preco)
            FROM curso c2
        ) THEN 'ACIMA_DA_MEDIA'
        WHEN c.preco = (
            SELECT AVG(c2.preco)
            FROM curso c2
        ) THEN 'NA_MEDIA'
        ELSE 'ABAIXO_DA_MEDIA'
        END AS classificacao_preco
FROM curso c
         LEFT JOIN compra co
                   ON co.id_curso = c.id_curso
GROUP BY
    c.id_curso,
    c.nome,
    c.preco;

CREATE INDEX IF NOT EXISTS idx_aula_id_curso_id_modulo
    ON aula (id_curso, id_modulo);

CREATE INDEX IF NOT EXISTS idx_assistir_id_curso_cpf_aluno
    ON assistir (id_curso, cpf_aluno);